SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
SCREEN_TITLE = "Meteor Rush"

MAX_FPS = 60

# --- Constantes del Jugador ---
PLAYER_SCALING = 0.5
PLAYER_MOVEMENT_SPEED = 200
PLAYER_ROTATION_SPEED = 4

# --- Constantes de Asteroides ---
ASTEROID_INITIAL_COUNT = 3
ASTEROID_SPAWN_INTERVAL = 5.0
# --- Asteroide Grande ---
ASTEROID_BIG_MAX_HEALTH = 6
ASTEROID_BIG_COLLISION_DAMAGE = 5
ASTEROID_BIG_SPEED_MIN = 0.5
ASTEROID_BIG_SPEED_MAX = 1.0
ASTEROID_BIG_ROTATION_SPEED_MIN = -0.5
ASTEROID_BIG_ROTATION_SPEED_MAX = 0.5
ASTEROID_BIG_SCALING = 1.5
# --- Asteroide Mediano ---
ASTEROID_MID_MAX_HEALTH = 3
ASTEROID_MID_COLLISION_DAMAGE = 3
ASTEROID_MID_SPEED_MIN = 0.9
ASTEROID_MID_SPEED_MAX = 2.0
ASTEROID_MID_ROTATION_SPEED_MIN = -2.5
ASTEROID_MID_ROTATION_SPEED_MAX = 2.5
ASTEROID_MID_SCALING = 1
# --- Asteroide Pequeño ---
ASTEROID_SML_MAX_HEALTH = 1
ASTEROID_SML_COLLISION_DAMAGE = 1
ASTEROID_SML_SPEED_MIN = 1.0
ASTEROID_SML_SPEED_MAX = 3.0
ASTEROID_SML_ROTATION_SPEED_MIN = -4.5
ASTEROID_SML_ROTATION_SPEED_MAX = 4.5
ASTEROID_SML_SCALING = 0.75
# --- Asteroide Mini ---
ASTEROID_TIN_MAX_HEALTH = 1
ASTEROID_TIN_COLLISION_DAMAGE = 1
ASTEROID_TIN_SPEED_MIN = 3.0
ASTEROID_TIN_SPEED_MAX = 6.0
ASTEROID_TIN_ROTATION_SPEED_MIN = -8
ASTEROID_TIN_ROTATION_SPEED_MAX = 8
ASTEROID_TIN_SCALING = 0.5