SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
SCREEN_TITLE = "Meteor Rush"

MAX_FPS = 60

# --- Constantes del Jugador ---
PLAYER_SCALING = 0.5
PLAYER_MOVEMENT_SPEED = 200
PLAYER_ROTATION_SPEED = 4

# --- Constantes de Asteroides ---
ASTEROID_SCALING = 0.5
ASTEROID_INITIAL_COUNT = 3
ASTEROID_SPAWN_INTERVAL = 5.0
ASTEROID_MIN_SPEED = 0.5
ASTEROID_MAX_SPEED = 2.0
ASTEROID_MIN_ROTATION_SPEED = -1.5
ASTEROID_MAX_ROTATION_SPEED = 1.5